name: cde_tadf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - jsonnet=0.17.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.2
  - python=3.7.13
  - python_abi=3.7
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.2
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
      - alabaster==0.7.12
      - allennlp==0.9.0
      - appdirs==1.4.4
      - asgiref==3.5.0
      - attrs==21.4.0
      - babel==2.10.1
      - beautifulsoup4==4.6.3
      - blis==0.2.4
      - boto3==1.15.18
      - botocore==1.18.18
      - cached-property==1.5.2
      - cffi==1.15.0
      - chardet==3.0.4
      - click==6.7
      - conllu==1.3.1
      - cryptography==36.0.2
      - cssselect==1.1.0
      - cycler==0.11.0
      - cymem==2.0.6
      - dawg-patched==0.9.1
      - deprecation==2.1.0
      - django==3.2.13
      - docutils==0.17.1
      - editdistance==0.6.0
      - en-core-web-sm==2.1.0
      - flaky==3.7.0
      - flask==1.1.4
      - flask-cors==3.0.10
      - fonttools==4.33.2
      - ftfy==6.1.1
      - gevent==21.12.0
      - greenlet==1.1.2
      - h5py==3.6.0
      - idna==2.8
      - imagesize==1.3.0
      - importlib-metadata==4.11.3
      - iniconfig==1.1.1
      - itsdangerous==1.1.0
      - jinja2==2.11.3
      - jmespath==0.10.0
      - joblib==1.1.0
      - jsonpickle==2.1.0
      - kiwisolver==1.4.2
      - lxml==4.8.0
      - markupsafe==2.1.1
      - matplotlib==3.5.1
      - mpi4py==3.1.3
      - mpmath==1.2.1
      - murmurhash==1.0.6
      - nltk==3.7
      - numpy==1.21.6
      - numpydoc==1.2.1
      - overrides==3.1.0
      - packaging==21.3
      - pandas==1.3.5
      - parsimonious==0.9.0
      - pdfminer-six==20220319
      - pillow==9.1.0
      - plac==0.9.6
      - pluggy==1.0.0
      - preshed==2.0.1
      - prettytable==0.7.2
      - protobuf==3.20.1
      - py==1.11.0
      - pycparser==2.21
      - pygments==2.12.0
      - pyparsing==3.0.8
      - pytest==7.1.2
      - python-crfsuite==0.9.8
      - python-dateutil==2.8.2
      - pytorch-pretrained-bert==0.6.2
      - pytorch-transformers==1.1.0
      - pytz==2022.1
      - pyyaml==6.0
      - regex==2022.4.24
      - requests==2.21.0
      - responses==0.10.15
      - s3transfer==0.3.7
      - scikit-learn==0.22.1
      - scipy==1.7.3
      - selenium==3.141.0
      - sentencepiece==0.1.96
      - six==1.16.0
      - snowballstemmer==2.2.0
      - spacy==2.1.9
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - sqlparse==0.4.2
      - srsly==1.0.5
      - sympy==1.10.1
      - tabledataextractor==1.5.10
      - tensorboardx==2.5
      - termcolor==1.1.0
      - thinc==7.0.8
      - tokenizers==0.12.1
      - tomli==2.0.1
      - torch==1.11.0
      - tqdm==4.64.0
      - typing-extensions==4.2.0
      - unidecode==1.3.4
      - urllib3==1.24.3
      - wasabi==0.9.1
      - wcwidth==0.2.5
      - werkzeug==1.0.1
      - word2number==1.1
      - yaspin==2.1.0
      - zipp==3.8.0
      - zope-event==4.5.0
      - zope-interface==5.4.0
# prefix: $CONDA_PREFIX
